### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by andyyuan78** [taillefu/MonteCarloCuda#1]
ubgpu@ubgpu:~/github/MonteCarloCuda$ make all
nvcc -arch sm_21 --use_fast_math  -O3 -g -pg -lineinfo --ptxas-options=-v -ccbin gcc --compiler-options -pg,-O2,-g `pkg-config --cflags gsl cuda55 mkl1 popt `  -DHAVE_CUDA -DENABLE_TIMING -pg -c Kagome4.cu -o Kagome4.o
Package cuda55 was not found in the pkg-config search path.
Perhaps you should add the directory containing `cuda55.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cuda55' found
Package mkl1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `mkl1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mkl1' found
Package popt was not found in the pkg-config search path.
Perhaps you should add the directory containing `popt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'popt' found
Kagome4.cu:8:18: fatal error: mkl.h: No such file or directory
 #include <mkl.h> 
                  ^
compilation terminated.
make: *** [KagomeCudaFloat] Error 1
ubgpu@ubgpu:~/github/MonteCarloCuda$

**Comment by taillefu** [comment]
Hi andy,

this is a code for a research project so you will most probably find that it does not compile without a few things set up properly. What is missing is pretty much the pkgconfig file for cuda and mkl (which i did not include in the repository) so if you really want to use this code please ask me first. 

The code is fairly simple but it is highly specialized to the problem I study. It won't work without adapting it to the problem you are interested in.

cheers

Mathieu

**Comment by andyyuan78** [comment]
waiting you make it robust.
;)

**Comment by taillefu** [comment]
As I asked, what is your purpose? Making it more robust is meaningless to me since it is not designed to be shared on the first basis. I will add the missing files but you will have to modify them to suit your environment. You need the intel compiler and of the cuda sdk.

M.
